const AIRPORT_URL_BASE = 'https://s1-fmt2.liveatc.net';
const DEFAULT_AIRPORT_CODE = 'OVB';
const DEFAULT_MUSIC_ID = 0;
const DEFAULT_MUSIC_VOLUME = 1;
const DEFAULT_AIRPORT_VOLUME = 0.85;

export {
  AIRPORT_URL_BASE,
  DEFAULT_AIRPORT_CODE,
  DEFAULT_MUSIC_ID,
  DEFAULT_MUSIC_VOLUME,
  DEFAULT_AIRPORT_VOLUME,
};
